import type {
  AmenityKey,
  Booking,
  CategoryKey,
  Conversation,
  Property,
} from './types'

export const categories: {
  key: CategoryKey
  label: string
  icon: string
}[] = [
  { key: 'all', label: 'الكل', icon: 'Sparkles' },
  { key: 'pool', label: 'بمسبح', icon: 'Waves' },
  { key: 'family', label: 'عائلية', icon: 'Users' },
  { key: 'solar', label: 'طاقة شمسية', icon: 'Sun' },
  { key: 'vip', label: 'شقق VIP', icon: 'Crown' },
  { key: 'farm', label: 'مزارع', icon: 'Trees' },
  { key: 'chalet', label: 'شاليهات', icon: 'Umbrella' },
  { key: 'desert', label: 'استراحات صحراوية', icon: 'Tent' },
]

export const amenityLabels: Record<AmenityKey, { label: string; icon: string }> =
  {
    pool: { label: 'مسبح خاص', icon: 'Waves' },
    indoorPool: { label: 'مسبح مغلق', icon: 'Waves' },
    solar: { label: 'طاقة شمسية', icon: 'Sun' },
    generator: { label: 'مولد خاص', icon: 'Zap' },
    fiber: { label: 'إنترنت فايبر', icon: 'Wifi' },
    ac: { label: 'تكييف', icon: 'Wind' },
    parking: { label: 'موقف سيارات', icon: 'Car' },
    kitchen: { label: 'مطبخ مجهز', icon: 'ChefHat' },
    seaView: { label: 'إطلالة بحرية', icon: 'Eye' },
    garden: { label: 'حديقة', icon: 'Trees' },
    playground: { label: 'ملعب أطفال', icon: 'Baby' },
    security: { label: 'أمن وحراسة', icon: 'ShieldCheck' },
    water: { label: 'خزان مياه', icon: 'Droplets' },
    bbq: { label: 'منطقة شواء', icon: 'Flame' },
  }

export const cities = [
  'طرابلس',
  'بنغازي',
  'مصراتة',
  'الزاوية',
  'صبراتة',
  'البيضاء',
  'طبرق',
  'سبها',
  'غدامس',
  'الخمس',
]

export const properties: Property[] = [
  {
    id: 'p1',
    title: 'فيلا فاخرة بمسبح خاص وإطلالة على البحر',
    city: 'طرابلس',
    area: 'حي الأندلس',
    categories: ['pool', 'vip', 'family'],
    images: [
      '/images/villa-pool-1.png',
      '/images/villa-pool-2.png',
      '/images/villa-pool-3.png',
    ],
    price: 850,
    rating: 4.92,
    reviews: 128,
    guests: 10,
    bedrooms: 4,
    beds: 6,
    baths: 3,
    highlights: ['مسبح خاص', 'طاقة شمسية', 'مولد خاص'],
    amenities: [
      'pool',
      'solar',
      'generator',
      'fiber',
      'ac',
      'parking',
      'kitchen',
      'seaView',
      'security',
      'bbq',
    ],
    description:
      'فيلا حديثة على مساحة 600م² في حي الأندلس، تتميز بمسبح خاص ومساحات خارجية واسعة. مجهزة بالكامل بالطاقة الشمسية ومولد احتياطي لضمان الكهرباء على مدار الساعة. مناسبة للعائلات الكبيرة والمناسبات الخاصة.',
    host: {
      name: 'خالد المبروك',
      avatar: '/images/host-1.png',
      since: '2021',
      phone: '218913456789',
      responseTime: 'يرد عادة خلال ساعة',
    },
    instantBook: true,
    isSuperhost: true,
    minNights: 2,
  },
  {
    id: 'p2',
    title: 'شقة VIP بإطلالة بانورامية على الكورنيش',
    city: 'طرابلس',
    area: 'شارع الشط',
    categories: ['vip', 'family'],
    images: ['/images/apartment-vip-1.png', '/images/apartment-vip-2.png'],
    price: 420,
    rating: 4.85,
    reviews: 96,
    guests: 5,
    bedrooms: 2,
    beds: 3,
    baths: 2,
    highlights: ['إطلالة بحرية', 'إنترنت فايبر', 'مولد خاص'],
    amenities: [
      'seaView',
      'fiber',
      'generator',
      'ac',
      'parking',
      'kitchen',
      'security',
    ],
    description:
      'شقة عصرية في الطابق الثاني عشر بإطلالة مباشرة على البحر المتوسط وكورنيش طرابلس. تشطيب فندقي، إنترنت فايبر سريع مناسب للعمل عن بعد، ومصعد وأمن على مدار الساعة.',
    host: {
      name: 'سالم الفيتوري',
      avatar: '/images/host-1.png',
      since: '2022',
      phone: '218924567890',
      responseTime: 'يرد عادة خلال 30 دقيقة',
    },
    instantBook: true,
    minNights: 1,
  },
  {
    id: 'p3',
    title: 'مزرعة واسعة بأشجار الزيتون ومسبح',
    city: 'الزاوية',
    area: 'طريق الساحل',
    categories: ['farm', 'pool', 'family', 'solar'],
    images: ['/images/farm-1.png', '/images/farm-2.png'],
    price: 600,
    rating: 4.78,
    reviews: 64,
    guests: 15,
    bedrooms: 3,
    beds: 8,
    baths: 2,
    highlights: ['مسبح خاص', 'طاقة شمسية', 'منطقة شواء'],
    amenities: [
      'pool',
      'solar',
      'generator',
      'garden',
      'bbq',
      'parking',
      'kitchen',
      'water',
      'playground',
    ],
    description:
      'مزرعة على مساحة 3 هكتارات بها أشجار زيتون ونخيل، مسبح كبير، ومنطقة جلسات خارجية مع بركولا. مثالية للعزائم العائلية والرحلات الجماعية. تعمل بالطاقة الشمسية بالكامل مع مولد احتياطي.',
    host: {
      name: 'عبدالسلام القذافي',
      avatar: '/images/host-1.png',
      since: '2020',
      phone: '218915678901',
      responseTime: 'يرد عادة خلال ساعتين',
    },
    instantBook: false,
    isSuperhost: true,
    minNights: 1,
  },
  {
    id: 'p4',
    title: 'شاليه على البحر مباشرة بجلسة خارجية',
    city: 'صبراتة',
    area: 'شاطئ صبراتة',
    categories: ['chalet', 'family'],
    images: ['/images/chalet-1.png', '/images/chalet-2.png'],
    price: 350,
    rating: 4.67,
    reviews: 41,
    guests: 6,
    bedrooms: 2,
    beds: 4,
    baths: 1,
    highlights: ['على البحر', 'مولد خاص', 'منطقة شواء'],
    amenities: [
      'seaView',
      'generator',
      'bbq',
      'ac',
      'kitchen',
      'parking',
      'water',
    ],
    description:
      'شاليه على الشاطئ مباشرة، تفصلك عن البحر خطوات قليلة. تراس خارجي مع جلسة ومنطقة شواء، مناسب للعائلات الصغيرة ورحلات نهاية الأسبوع.',
    host: {
      name: 'محمد الزوي',
      avatar: '/images/host-1.png',
      since: '2023',
      phone: '218926789012',
      responseTime: 'يرد عادة خلال 3 ساعات',
    },
    instantBook: true,
    isNew: true,
    minNights: 2,
  },
  {
    id: 'p5',
    title: 'منزل عائلي واسع بحوش كبير وملعب أطفال',
    city: 'بنغازي',
    area: 'الفويهات',
    categories: ['family', 'solar'],
    images: ['/images/family-1.png', '/images/family-2.png'],
    price: 480,
    rating: 4.88,
    reviews: 87,
    guests: 12,
    bedrooms: 5,
    beds: 7,
    baths: 3,
    highlights: ['حوش واسع', 'طاقة شمسية', 'ملعب أطفال'],
    amenities: [
      'solar',
      'generator',
      'garden',
      'playground',
      'ac',
      'parking',
      'kitchen',
      'water',
      'fiber',
    ],
    description:
      'منزل من طابقين في منطقة الفويهات الهادئة، يتسع لعائلتين. صالة استقبال عربية تقليدية، حوش كبير مبلط مع ملعب أطفال، ونظام طاقة شمسية يغطي احتياج المنزل.',
    host: {
      name: 'أحمد بن حليم',
      avatar: '/images/host-1.png',
      since: '2021',
      phone: '218917890123',
      responseTime: 'يرد عادة خلال ساعة',
    },
    instantBook: false,
    isSuperhost: true,
    minNights: 3,
  },
  {
    id: 'p6',
    title: 'فيلا صديقة للبيئة بمسبح مغلق وطاقة شمسية',
    city: 'مصراتة',
    area: 'قصر أحمد',
    categories: ['solar', 'pool', 'vip'],
    images: ['/images/solar-villa-1.png', '/images/solar-villa-2.png'],
    price: 720,
    rating: 4.95,
    reviews: 53,
    guests: 8,
    bedrooms: 3,
    beds: 5,
    baths: 3,
    highlights: ['مسبح مغلق', 'طاقة شمسية', 'مولد خاص'],
    amenities: [
      'indoorPool',
      'solar',
      'generator',
      'fiber',
      'ac',
      'parking',
      'kitchen',
      'garden',
      'security',
    ],
    description:
      'فيلا حديثة تعمل بالكامل على الطاقة الشمسية مع بطاريات تخزين، بها مسبح مغلق قابل للتدفئة يعمل طوال السنة. تشطيب راقٍ وتراس علوي مع إطلالة على المدينة.',
    host: {
      name: 'إبراهيم الشريف',
      avatar: '/images/host-1.png',
      since: '2022',
      phone: '218918901234',
      responseTime: 'يرد عادة خلال 45 دقيقة',
    },
    instantBook: true,
    minNights: 2,
  },
  {
    id: 'p7',
    title: 'استراحة صحراوية تقليدية في غدامس القديمة',
    city: 'غدامس',
    area: 'المدينة القديمة',
    categories: ['desert', 'family'],
    images: ['/images/desert-1.png'],
    price: 260,
    rating: 4.71,
    reviews: 29,
    guests: 7,
    bedrooms: 3,
    beds: 5,
    baths: 2,
    highlights: ['طراز تقليدي', 'طاقة شمسية', 'جلسة صحراوية'],
    amenities: ['solar', 'generator', 'garden', 'bbq', 'kitchen', 'water', 'ac'],
    description:
      'بيت تقليدي من الطين في مدينة غدامس المدرجة في قائمة اليونسكو، ترميم كامل مع الحفاظ على الطابع الأصلي. جلسات صحراوية مسائية وجولات إلى الكثبان الرملية.',
    host: {
      name: 'يوسف الغدامسي',
      avatar: '/images/host-1.png',
      since: '2023',
      phone: '218919012345',
      responseTime: 'يرد عادة خلال 4 ساعات',
    },
    instantBook: false,
    isNew: true,
    minNights: 2,
  },
  {
    id: 'p8',
    title: 'شقة مفروشة قريبة من وسط المدينة',
    city: 'بنغازي',
    area: 'شارع دبي',
    categories: ['vip', 'family'],
    images: ['/images/apartment-vip-2.png', '/images/apartment-vip-1.png'],
    price: 300,
    rating: 4.6,
    reviews: 72,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 1,
    highlights: ['إنترنت فايبر', 'مولد خاص', 'موقف خاص'],
    amenities: ['fiber', 'generator', 'ac', 'parking', 'kitchen', 'water'],
    description:
      'شقة مفروشة بالكامل على بعد دقائق من وسط بنغازي والمطاعم والأسواق. مناسبة لرجال الأعمال والعائلات الصغيرة، مع إنترنت فايبر ومولد يعمل تلقائياً.',
    host: {
      name: 'نوري العبيدي',
      avatar: '/images/host-1.png',
      since: '2022',
      phone: '218921234567',
      responseTime: 'يرد عادة خلال ساعتين',
    },
    instantBook: true,
    minNights: 1,
  },
]

export const bookings: Booking[] = [
  {
    id: 'b1',
    propertyId: 'p1',
    checkIn: '2026-08-14',
    checkOut: '2026-08-18',
    guests: 8,
    nights: 4,
    total: 3400,
    status: 'upcoming',
  },
  {
    id: 'b2',
    propertyId: 'p4',
    checkIn: '2026-09-02',
    checkOut: '2026-09-05',
    guests: 5,
    nights: 3,
    total: 1050,
    status: 'upcoming',
  },
  {
    id: 'b3',
    propertyId: 'p3',
    checkIn: '2026-06-10',
    checkOut: '2026-06-12',
    guests: 12,
    nights: 2,
    total: 1200,
    status: 'completed',
  },
  {
    id: 'b4',
    propertyId: 'p8',
    checkIn: '2026-05-01',
    checkOut: '2026-05-03',
    guests: 3,
    nights: 2,
    total: 600,
    status: 'cancelled',
  },
]

export const conversations: Conversation[] = [
  {
    id: 'c1',
    propertyId: 'p1',
    hostName: 'خالد المبروك',
    hostAvatar: '/images/host-1.png',
    lastMessage: 'أهلاً بك، الفيلا متاحة في التواريخ المطلوبة والمسبح جاهز.',
    time: 'الآن',
    unread: 2,
  },
  {
    id: 'c2',
    propertyId: 'p4',
    hostName: 'محمد الزوي',
    hostAvatar: '/images/host-1.png',
    lastMessage: 'تمام، سأترك لك المفتاح مع الحارس عند الوصول.',
    time: 'أمس',
    unread: 0,
  },
  {
    id: 'c3',
    propertyId: 'p6',
    hostName: 'إبراهيم الشريف',
    hostAvatar: '/images/host-1.png',
    lastMessage: 'المسبح المغلق مدفأ ويعمل طوال السنة، لا تقلق.',
    time: 'قبل 3 أيام',
    unread: 0,
  },
]

export function getProperty(id: string) {
  return properties.find((p) => p.id === id)
}

export function formatPrice(value: number) {
  return new Intl.NumberFormat('ar-LY', { maximumFractionDigits: 0 }).format(
    value,
  )
}
